services:
  database:
    container_name: redis_container
    image: redis
    build: ./redis
    hostname: redishost
    ports:
      - "6379:6379"
  application:
    container_name: desafio_application
    image: desafio-ia:0.0.1-SNAPSHOT
    links:
      - database
    ports:
      - "8080:8080"